### ISSUE TITLE
Add support for TYPO3 v.8

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#139]
* Bump version constrains
* Adjust code to be supported by TYPO3 v8
* Adjust .travis.yml to run v8 with php v7

**Comment by tomasnorre** [comment]
* Bump version constrains
* Adjust .travis.yml to run v8 with php v7

Are both handled in #ad3f3467e362a4005de311799b5ca7c14b70d9cc

**Comment by maechler** [comment]
@tomasnorre Is there a rough timeline for a release that supports TYPO3 v8?

**Comment by tomasnorre** [comment]
@maechler The is already a TYPO3_8 branch, but no official release.. 

We currently don't have any timeline for the official release. (Read limited time for maintainance atm. :( )

**Comment by eisbehr-** [comment]
Just to ask, can we assume the projects is dead in the future then? I mean, we're in the halftime of v8 LTS, with now one year left of full support. Even a year after this issue is open, there is no release of an v8 version planed. So it seems pretty insecure to relay on this project in the future, am I right? I mean, if you possible release a version for v8 sometime, we're possible on v9 already. 😉

I'm just asking you to see where this project stands and sees itself in the future. Maybe you suggest to better look for alternatives in the future. It's a great extension. But with no support nobody could build websites with it anymore ...

Thanks!

**Comment by tomasnorre** [comment]
HI @eisbehr- 

We are for sure trying to keep support for this, and we will be happy to do this. The question is as always the time that needs to be invested.

We are planning to do a full rewrite of the extension, which will be 8 compatible, and not backwards compatible. Our plan is to have this as a new start. 

We are still considering how we can do this, to get it does and correct and soon as possible, but it isn't that straightforward to just pull out 2 Weeks and rewrite the extension. 

I really appreciate your feedback, i'm sorry that it's taking this long, but we are also just doing this in our free time, not all features can be done within regular working hours.
