### ISSUE TITLE
Scheduler Tasks broken after upgrade to 5.1.1 (composer)

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#154]
This is open to separate concerns from issue #142

**Comment by tomasnorre** [comment]
@rvock can I ask you to test this branch? 

branch: issue/154

**Comment by rvock** [comment]
Thanks, this branch works when installed via composer :)

**Comment by tomasnorre** [comment]
Super. Thanks for confirming and reporting @rvock

**Comment by tomasnorre** [comment]
There is a new release ready @rvock 5.1.2

**Comment by rvock** [comment]
Thanks, this release works :)

But, there's a "but": I need to install the release with the composer name `aoepeople/crawler` instead of `typo3-ter/crawler`.

The package.json for `typo3-ter/crawler` does not contain the extra-field:
https://composer.typo3.org/p/typo3-ter/crawler$da861fbb8e946f89b492a2ee282ef5cae369cef982942fbec9898f5e224c0e35.json

`aoepeople/crawler` does contain it:
https://composer.typo3.org/p/aoepeople/crawler$d1ac353364f1a3f68cab472198df024a5f1b77643fa372413db53b4ba229e4f1.json

I am not sure, if this is your error or a bug of composer.typo3.org, but I believe, it's a bug of the automatic conversion of TER-packages for composer.typo3.org using [CmsComposerPackageGenerator](https://github.com/TYPO3/CmsComposerPackageGenerator/) :
[CreateTerExtensionJsonCommand.php#L144](https://github.com/TYPO3/CmsComposerPackageGenerator/blob/0ab57d/src/Classes/Command/CreateTerExtensionJsonCommand.php#L144)

**Comment by tomasnorre** [comment]
Thanks @rvock for the information, I happen to be in the TYPO3.org team as well, so gives me opportunity to investigate on both sites ;) 

Thanks for you feedback
