### ISSUE TITLE
[Bug] Potential SQL injection vulnerability

### ISSUE THREAD

**Issue by sangantnk8** [AOEpeople/crawler#333]
Hi,

I found the function countEntriesInQueueForPageByScheduleTime does not filter the input (pageuid and schedule_timestamp) before prepare the SQL query. it means this function has a SQL injection Vulnerability.

Link: https://github.com/AOEpeople/crawler/blob/master/Classes/Api/CrawlerApi.php#L201

**Comment by tomasnorre** [comment]
Thanks, 

Will have a look.

**Comment by ohader** [comment]
### Security Assessment

Scope: Method `countEntriesInQueueForPageByScheduletime`

That's really just a "potential" issue. The method in question was not used anymore like this in recent versions - thus the vulnerability affects custom derived extensions XCLASSing the class in question and calling the protected method.

The protected method has been introduced in this commit:

https://github.com/AOEpeople/crawler/blob/d18077c037311dd3946cb5499e334cfeedfb56af/class.tx_crawler_api.php#L104

Usage of the method was
* https://github.com/AOEpeople/crawler/commit/d18077c037311dd3946cb5499e334cfeedfb56af#diff-eb0690a1e8f2007ade1a39688afd20ddR104 - start using method, with casted values (some lines above usage)
* https://github.com/AOEpeople/crawler/commit/20dffb8a9989852ec9d28dd156affc370def691e#diff-eb0690a1e8f2007ade1a39688afd20ddL115 - stop using method in whole extension

Since then this method `countEntriesInQueueForPageByScheduletime` is a left over from earlier refactoring which was used between June 2019 and Sept 2009 (TYPO3 v4.2, TYPO3 v4.3-beta).

### Conclusion

By statically analyzing just the method and the SQL statement it is a classic SQL injection vulnerability. By setting everything into context and determine a real attack vector it's not a vulnerability at all and the fix can be considered as "code clean up" instead of a "security fix".

### Security Contact

In case there still is a real vulnerability that I did overlook, please don't hesitate and report back to [security@typo3.org](mailto:security@typo3.org)
