### ISSUE TITLE
[FEATURE] Add StaticfileCache support

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#497]
Please check if the nc_staticfile_cache hook can be remove, if not we need to replace it with a new hook.

- [x] Remove current nc_staticfile_cache hook

**Comment by lochmueller** [comment]
Hey @tomasnorre 
If y new hook is needed I could add it to staticfilecache. Could you explain the purpose of the hook and why it is needed?
Regards,
Tim

**Comment by tomasnorre** [comment]
Hi @lochmueller,

Thanks for reaching out. I'll look into this and get back to you. You might have more knowledge than me where the right place is to implement it.

I'll describe the use case and then you can look into the implementation. 
Hook, Signal or Middleware.

I'll get back to you.

**Comment by lochmueller** [comment]
Note: If the hook is only this implementation: https://github.com/AOEpeople/crawler/blob/typo3v9/Classes/Hooks/StaticFileCacheCreateUriHook.php I think the hook could  just dropped, becuase there are no `'#^/index.php\?&?id=(\d+)(&.*)?$#'` URI since TYPO3 > 9.0.  But I can also be wrong, because I do not know the whole crawler implementation/logic.

**Comment by tomasnorre** [comment]
It's exactly that hook i'm talking about.

I'm also not sure about this crawler logic regarding this hook. I've asked the develop doing it, then I'll get back to you. 

But my expectation is also that it can be dropped.

**Comment by tomasnorre** [comment]
Hi @lochmueller,

We would not need this hook anymore. I'll remove it from the crawler when it turns out that I'm wrong we can always add it back.

The hook is for RealURL which is not needed in TYPO3 9 LTS, because of the SiteHandling.
