### ISSUE TITLE
Add progress bar to cli commands

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#627]
## Feature Request

It would be great to have some progress bar, e.g. https://symfony.com/doc/current/components/console/helpers/progressbar.html for the CLI commands to see and progress. 

**Describe alternatives you've considered**
https://symfony.com/doc/current/components/console/helpers/progressbar.html

**Comment by carstendietrich** [comment]
Hey @tomasnorre 
is there already somebody working on this? I'm a little bit low on Hacktoberfest contributions this year so why not going back to my TYPO3 roots 😁 

Had a quick look at the commands that the extension registers, guess there are only two that could benefit from a progress bar. That would be `crawler:buildQueue` with the `--mode exec` and then the `crawler:crawlQueue` command. The first one should be pretty straightforward since most of the output already happens within the command the second one could be more complex due to the fact that most of the logic lives in the `CrawlerController` and that there is currently only debug output using `echo`.

Do you want to have two PR's for split by the command or should I provide a single one? Any preferences on the progress bar styling or should I use the default Symonfy one? There is also `SymfonyStyle` which wraps the progress bar and stuff like interactive dialogs with some neat helpers: https://symfony.com/doc/current/console/style.html#basic-usage maybe worth having a look down the road.

**Comment by tomasnorre** [comment]
Hi @carstendietrich 

I didn't know you did TYPO3 too ;) 

No one is working on this, as far as I know so feel free to add this, that would be really cool.
I think one PR should be enough, but depending in the size of them, you can decide if you want to split them into one or two.

**Comment by tomasnorre** [comment]
I just read your comment again. I think I would split it into two PRs.

The CrawlerController is a little more sensitive to changes, so could have a little more ping-pong before it gets accepted, so I think splitting them into two would give a better overview of the change and have an earlier progress

**Comment by carstendietrich** [comment]
> I just read your comment again. I think I would split it into two PRs.
> 
> The CrawlerController is a little more sensitive to changes, so could have a little more ping-pong before it gets accepted, so I think splitting them into two would give a better overview of the change and have an earlier progress

Cool that's what I thought as well. I'll start with the crawler:buildQueue since it should be an easy win 😎
