### ISSUE TITLE
[BUG] Error 500 if crawler configured with a `fegroups` in TYPO3 9LTS

### ISSUE THREAD

**Issue by rintisch** [AOEpeople/crawler#643]
## Bug Report

**Current Behavior**
If a crawler configuration is configured with an entry in `fegroups` the cache is not created and the backend module _Info_ → _Site Crawler_ → _Crawler Log_ shows in column _Status_ `Error: 500 Internal Server Error...` when the crawler tried to crawl the page
![grafik](https://user-images.githubusercontent.com/44193208/97535690-4d846380-19bc-11eb-9934-224630344d62.png)

**Expected behavior/output**
Crawling shall also work with entries in field `fegroups`.

**Environment**
- Crawler version(s): 9.1.2-dev
- TYPO3 version(s): 9.5.22
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Additional context**
* It works if the crawler is configured without an entry in `fegroups`.
* This issue emerged from #637

**Comment by tomasnorre** [comment]
This is related to #617 which was surposed to be fixed in https://github.com/AOEpeople/crawler/commit/f1a095cf0f236cf6c2d5eb9285b3e678bc1fd3fb. Unfortunately it does not look like that's the case. 

It looks like we only fixed this for TYPO3 10, without proper testing for  TYPO3 9.
I'll see what I can do to have this fixed for both versions. 

The parent commit of the merge for issue #617 is working in TYPO3 9. 
https://github.com/AOEpeople/crawler/commit/9aa959136bc5ce2f95a18aea789dbf67df8ef8ab

@rintisch Can you please confirm that the last linked commit is working for you too.? 

Then I'll see what I can do. Would like to avoid and if/else on TYPO3 version.

**Comment by tomasnorre** [comment]
@rintisch can you please check that this PR fixes your problem. 
https://github.com/AOEpeople/crawler/pull/646

Thanks

**Comment by rintisch** [comment]
@tomasnorre this PR works. 
Thank you! I cannot test as fast as you fix ;)

**Comment by tomasnorre** [comment]
Thanks I'll make sure it gets merged and a new release made. 

I'm just really happy that having interaction and feedback, this motivates me a lot to have fixes done fast. 
Thank you so much.

**Comment by tomasnorre** [comment]
New release 9.1.2 is out.
