### ISSUE TITLE
It's not possible to mass-edit "Base url" field in the crawler configuration

### ISSUE THREAD

**Issue by tmotyl** [AOEpeople/crawler#78]
Steps to reproduce:
1. Go to the list view
2. Click on the "Crawler Configuration" table header
3. Add "Base url" column to the table

Actual: base url column is empty
Expected: base url column is filled with data
1. Click on the pencil icon to mass edit

Actual: base url selectors will not appear
Expected: base url selectors will be visible

TYPO3 6.2.19

**Comment by tomasnorre** [comment]
Thanks @tmotyl 

Will add it to the list of next fixes..

**Comment by tomasnorre** [comment]
HI @tmotyl 

This is due to the displayCond ( 'displayCond' => 'FIELD:sys_domain_base_url:=:0',) in the TCA for base_url-field.. If there is already set a domain from sys_domains the base_url will not be rendered with the mass-edit.

Can you please confirm this? 

I don't consider this a bug, but i'm for sure up for discussion what would be best behaviour to optimise the user experience for the extension.

/Tomas

**Comment by tmotyl** [comment]
What is the purpose of this display condition?

**Comment by tomasnorre** [comment]
haha, that's actually a good point, i'm not sure i know the answer, perhaps @srotsch can answer that. :)

To me it looks like it has no point of being there, and therefor should be removed, and they the mass-edit will work again too :)

**Comment by tomasnorre** [comment]
Hi @tmotyl 

After looking into this it make perfectly sense to us that the display condition is there, as you don't want to set a base_url manually if sys_domain is set.

Therefore the field is also no displayed in mass edit.

Please give us some examples of you use case so that we can understand why the problem lies in this behaviour.

**Comment by tomasnorre** [comment]
Ping @tmotyl

**Comment by tomasnorre** [comment]
@tmotyl Is this still an issue for you, if it's please reopen the issue. I want to clean up the issue-tracker..
