### ISSUE TITLE
Fatal error: Class 'tx_realurl' not found (TYPO3 7.6.5, realurl 2.0.11)

### ISSUE THREAD

**Issue by dklimpel** [AOEpeople/crawler#87]
Execute the crawler in BE module "info" crashes:
Fatal error: Class 'tx_realurl' not found in /home/www/nordwest/typo3_src-7.6.5/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4533

TYPO3 7.6.5
realurl 2.0.11
crawler  5.0.4

**Comment by tomasnorre** [comment]
Thanks for reporting @dklimpel.
Will take a look as soon as possible.

**Comment by tomasnorre** [comment]
@dklimpel  I bet this is because the realUrl extension have been namespaced? 

I'll talk to one of the other maintainer on how to deal with this, which version should be supported.

**Comment by dklimpel** [comment]
I think that is the problem. The class 'tx_realurl' does not exist anymore in realurl 2.
In my opinion everybody should uses namespaces. TYPO3 4.5 is end of life. The newer versions of TYPO3 support namespaces. The old version (1.x) of realurl is no longer supported, too.

https://typo3.org/extensions/repository/view/realurl
> This is the last maintanance release of realurl 1.x. It is also the last version of realurl that supports TYPO3 4.5. The next version will be realurl 2.0.0 and it will support only TYPO3 6.2 or newer. You may still use this version with TYPO3 4.5 but it w 
Supports TYPO3 version 4.5.40 - 7.9.999 
> Version 1.13.6, January 29, 2016

**Comment by tomasnorre** [comment]
Hi @dklimpel  

We understand your problem, but currently the Crawler is not supporting RealURL 2.0, we will set the RealURL dependencies for the extensions, so you would get aware of this earlier. 

Then we will come up with a way to support both 1.x and 2.x as to many projects still depends on RealURL 1.x

**Comment by motordigital** [comment]
I fixed this issues based on version 5.0.9. You can see it here within my fork https://github.com/motordigital/crawler/commit/04ab00cc8fadf0452e0860b84c1f434923692197

Attention: due to a lot of changes on your develop branch, the fix cannot be merged to develop without conflicts. And the develop branch made problems on my project, so I kept on version 5.0.9 with that fix.

[class.tx_crawler_lib.php.zip](https://github.com/AOEpeople/crawler/files/519453/class.tx_crawler_lib.php.zip)

**Comment by dklimpel** [comment]
The fix works for me!

**Comment by dklimpel** [comment]
Since #130 `$this->initTSFE` is in function _readUrl_ not in ___construct_ anymore. This is to late. Realurl needs TSFE in function _urlListFromUrlArray_.

**Comment by tomasnorre** [comment]
@dklimpel for reporting this. 

We will dig into this when we get to it.

**Comment by anujaunds** [comment]
i didn't understand could you sent me proper step what i can do for resolve this issue.

**Comment by tomasnorre** [comment]
@anujaunds There is no proper step yet, as RealURL 2.x still isn't supported. 

Sorry.

**Comment by tomasnorre** [comment]
Sounds like caching, if RealURL isn't installed at all it should not try to locate the class.

**Comment by sdesign6** [comment]
I've read the releated issues #87 #131 to the bug.
Is there a realistic chance or some progress to bring the crawling features of realurls back to TYPO3 8.7.x?

Thx
Sven

**Comment by tomasnorre** [comment]
@motordigital Would it be possible that you make your commit version independent, So that you make an version that is compatible with RealURL 1.x and 2.x 

You suggestion looks simple and straightforward. 
Perhaps introducing a RealURL Service/Utility that wrap this functionality to abstract the RealUrl functionality. 

Please let me know. Otherwise I'll look into this myself.

**Comment by tomasnorre** [comment]
@motordigital I've started a WIP on this topic. Feel free to comment. 

#88

**Comment by tomasnorre** [comment]
Sorry, but we will not add support for RealURL 2.x, we will focus on getting a TYPO3 9 LTS release out instead.
